services:
  fastapi:
    build: ./ai-chat-backend
    container_name: ai-chat-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/code/data
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - MODEL_API_KEY=${MODEL_API_KEY}
      - EMBEND_MODEL_URL=http://172.17.0.1:11434
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build: ./ai-chat-frontend
    container_name: react_app
    ports:
      - "80:80"   # Nginx 对外暴露 80
    depends_on:
      - fastapi

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
