name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.5 # 这是一个非常方便的 SSH Action
      with:
        host: ${{ secrets.SERVER_HOST }} # 从 Secrets 中读取服务器地址
        username: ${{ secrets.SERVER_USERNAME }} # 从 Secrets 中读取用户名
        key: ${{ secrets.SERVER_SSH_KEY }} # 从 Secrets 中读取私钥
        port: ${{ secrets.SERVER_PORT }} # 从 Secrets 中读取端口
        script: |
          cd ~/psycal-story

          git fetch && git reset --hard origin/main

          docker-compose down

          docker compose up -d --build

          docker image prune -f
